data:
    mnist:
        path: /datasets/mnist
        use_inverse: false
    svhn:
        path: /datasets/svhn
train:
    nb_iter: 12
    batch-size: 64
    gen_opti: adam
    disc_opti: adam
    lr_gen: 2e-4
    lr_disc: 2e-4
    gan_loss: original
    nb_iter_d: 1
    nb_iter_g: 1
    vae_init: 0
    loss_weight:
        gen: 1.
        disc: 1.
        classif_source: 10.
        classif_vae: 0.
        r1_reg: 0.
        vae_rec: 0.001
        vae_kl: 0.0001
        cycle: 0.
        entropy: 0.
        feat_matching: 0.0001
    test_every: 2 
    save_every: 5
test:
    batch-size: 100
networks:
    generator:
        encoder_name: unit_encoder
        decoder_name: unit_decoder
        channels: 96
        shared_weights: weak # {weak, strong, none}
    discriminator:
        name: unit_discriminator
        channels: 64
        shared_weights: strong # {weak, strong, none}
results:
    nb_images: 64
        
