data:
    mnist:
        path: /home/arthur/datasets/mnist
        use_inverse: false
    svhn:
        path: /home/arthur/datasets/svhn
train:
    nb_iter: 30000
    batch_size: 64
    gen_opti: adam
    disc_opti: adam
    lr_gen: 2e-4
    lr_disc: 2e-4
    gan_loss: original
    weight_clipping: 0 # if 0 or less, no weight clipping
    nb_iter_d: 1
    nb_iter_g: 1
    vae_init: 0
    loss_weight:
        gen: 1
        disc: 1
        classif_source: 1
        classif_vae: 1
        r1_reg: 1
        vae_rec: 10
        vae_kl: 10
        cycle: 0
        entropy: 0
        feat_matching: 0
    test_every: 10
    save_every: 500
test:
    batch_size: 100
networks:
    generator:
        encoder_name: unit_encoder
        decoder_name: unit_decoder
        channels: 96
        shared_weights: strong # {weak, strong, none}
    discriminator:
        name: unit_discriminator
        channels: 64
        shared_weights: strong # {weak, strong, none}
results:
    nb_images: 64
        
